### ISSUE TITLE
[Profile] Minor UI changes

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#154]
https://monosnap.com/file/XL4zVbdv3wLsvprK1BXE1fTqu9hXEm

**Comment by GildedHonour** [comment]
There's already the hover tooltip 'click to update your photo'. Should it be changed to 'click to update photo'?

**Comment by ezl** [comment]
@GildedHonour I am not seeing the behaviour you described.

This is what I see:
https://monosnap.com/file/xxxQC2TmwjD5hPcFscNK4vU9gyoQza

If you see that hover tooltip, please take a video and post back.

**Comment by GildedHonour** [comment]
@ezl Got it. I see a tooltip locally. Perhaps a new version hasn't been deployed on the server, let me check.

**Comment by GildedHonour** [comment]
The last time I was checking the server by mistake. 

Locally in the "dev" I have a different UI.

localhost, dev:

<img width="1097" alt="Captura de pantalla 2020-02-19 a la(s) 15 38 46" src="https://user-images.githubusercontent.com/2032888/74824565-428f1480-5300-11ea-9cc6-578c8d39c812.png">

server:

<img width="1173" alt="Captura de pantalla 2020-02-19 a la(s) 15 38 55" src="https://user-images.githubusercontent.com/2032888/74824600-52a6f400-5300-11ea-8bdc-eeac3e979faf.png">

@aldarund what's the version is deployed on the server?

**Comment by GildedHonour** [comment]
@aldarund in the "dev" branch the UI is different. How can I get the same UI as on the server run on the client?

**Comment by aldarund** [comment]
@GildedHonour i updated dev branch

**Comment by aldarund** [comment]
there was old profile.vue file, that was deleted locally but not pushed

**Comment by GildedHonour** [comment]
@aldarund at the dev 
> "There's already the hover tooltip 'click to update your avatar'."  

does the current branch on the server not include that tooltip?

**Comment by GildedHonour** [comment]
done

**Comment by GildedHonour** [comment]
at the server it's "click to update your avatar"

**Comment by ezl** [comment]
weirdly, i'm still seeing the "click to update avatar" tooltip showing not displaying correctly.

https://monosnap.com/file/8MyKHQJLpu6ZhuIDJnnunzixHlSJSv

appears to be a z-index issue.

@GildedHonour i see that your screenshots display it, but I'm not seeing it.

Using Firefox 74.0 on MacOS Mojave 10.14.6

**Comment by GildedHonour** [comment]
Confirmed, in Firefox.
It's caused by the css "top" value which is calculated on the fly somewhere in a library.
I'm looking into it.

**Comment by GildedHonour** [comment]
The "top" value of "v-tooltip" component is boolean.

https://vuetifyjs.com/en/components/tooltips/

2 ways to fix it:

1) use the alignment to left, bottom or right of "v-tooltip"

<img width="561" alt="Captura de pantalla 2020-03-23 a la(s) 17 11 13" src="https://user-images.githubusercontent.com/2032888/77314452-95902900-6cfd-11ea-8cdb-4e9f0f0d3e84.png">


2) move "user avatar" container 20 px to the bottom and continue to use "top"

<img width="829" alt="Captura de pantalla 2020-03-23 a la(s) 17 26 45" src="https://user-images.githubusercontent.com/2032888/77314469-9de86400-6cfd-11ea-99fb-f5f0af7cfb86.png">


I'm ok with either.
@ezl

**Comment by ezl** [comment]
got it. just move it to the right, then you can submit a PR and move this ticket to Done.

Thanks @GildedHonour
